### ISSUE TITLE
why masturbate when you can caturbate😜

### ISSUE THREAD

**Issue by trinhtobias** [wintersim/catCGI#1]
🤣🤣🤣🤣🤣🤣🤣🤣🤣😂😂😂😂😂🤣😂🤣😂🤣😂🐱‍🏍🐱‍🏍🐱‍🏍😂🤣😂👀👌👀👌👀👌👀❤🤦‍♀️❤🤦‍♀️🤦‍♂️❤🤦‍♂️❤🙌🤞🤞👍👍👍👍👍👍👍👍👍👍👍👍👍

**Comment by trinhtobias** [comment]
oopsie wrong repository 🤦‍♂️

**Comment by wintersim** [comment]
Sorry I don't understand your issue. Please clarify.

**Comment by trinhtobias** [comment]
😆✌😆✌🍆👀🍆👀😜🙌😜🗣
